### ISSUE TITLE
Foreach { ParseInt; ParseInt; eval()}

### ISSUE THREAD

**Issue by rakotomandimby** [rakrist08/flot-max#1]
https://github.com/rakrist08/flot-max/blob/626561c7d93e36a73a6e22d087bbf7779c43b14e/app.js#L180
Raha jerena maso fotsiny (tsy mbola executer-na, dia misy hitako fa azo hatsaraina, io section io.
**Marihiko fa tsy mbola executé ka tsy vita tena benchmark.**
Raha ny hevitro, ny fanaovana "ParseInt" sy "eval" dia mifanohitra aminy fitadiavana hafainganam-pandeha.

**Comment by rakrist08** [comment]
Marina ilay fanamariahana ary noraisina ny fanovana. Misaotra tompoko.
